//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequiemExperience.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RequiemExperience.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///bEnableKilling=1            ;0      1
        ///bEnableReading=1            ;       1
        ///bEnableSkillXP=0            ;0      0
        ///bForceLvlMeter=0            ;0      0
        ///bShowMessages=1             ;1      1
        ///bLocClearingFix=1           ;       1
        ///iMaxPlayerLevel=255         ;255    255
        ///fSkillCapBase=20            ;18.0   18.0
        ///fSkillCapMult=2.5           ;2.0    2.0
        ///bUseRacialCaps=0            ;1      1
        ///
        ///[Questing]
        ///iXPQuestMisc=0              ;0      25
        ///iXPQuestNone=15             ;75     50
        ///iXPQuestSi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Reward_Experience {
            get {
                return ResourceManager.GetString("Reward_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///bEnableKilling=1            ;0      1
        ///bEnableReading=1            ;       1
        ///bEnableSkillXP=0            ;0      0
        ///bForceLvlMeter=0            ;0      0
        ///bShowMessages=1             ;1      1
        ///bLocClearingFix=1           ;       1
        ///iMaxPlayerLevel=255         ;255    255
        ///fSkillCapBase=20            ;18.0   18.0
        ///fSkillCapMult=2.5           ;2.0    2.0
        ///bUseRacialCaps=0            ;1      1
        ///
        ///[Questing]
        ///iXPQuestMisc=0              ;0      25
        ///iXPQuestNone=15             ;75     50
        ///iXPQuestSi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string True_Experience {
            get {
                return ResourceManager.GetString("True_Experience", resourceCulture);
            }
        }
    }
}
