//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequiemExperience.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RequiemExperience.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Way to aggregate levels
        ///Mode: Mean
        ///
        ///## NPC EditorIDs ignore list
        ///Ignore: .*3DNPC.*      ;levels of 3DNPC entities are just random
        ///Ignore: callenhorker   ;level is out of place
        ///Ignore: DLC2Miraak.*   ;his human form spoils other humanoids
        ///Ignore: zzzCHMemory.*  ;VIGILANT is not really balanced for Requiem
        ///Ignore: Summon.*       ;levels of summonned entities shouldn&apos;t affect wild XP
        ///Ignore: EG_CONJ.*      ;same
        ///Ignore: MG05Messenger
        ///Ignore: DA14Summoned
        ///Ignore: DA14Sanguine
        ///Ignore: DA07VoiceMehrunesDagon
        ///I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string npcs {
            get {
                return ResourceManager.GetString("npcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Requiem installation quest = no XP
        ///REQ_Quest_Installation=Misc
        ///
        ///## Live Another Life = no XP
        ///ARTHLALChargenQuest=Misc
        ///MQ101=Misc
        ///ARTHLALRumorsOfWarQuest=None ;Helgen quest which kicks off main story = minimal XP
        ///MQ102=None ;Whiterun travel quest = minimal XP
        ///
        ///## SunHelm activation quest (type 8)
        ///_SHStartPrompt=Misc
        ///
        ///## Courier missives, minimal / small XP for all
        ///_M_Quest.*CourierLetterLow=None
        ///_M_Quest.*CourierLetterMed=None
        ///_M_Quest.*CourierLetterHigh=SideQuest
        ///_M_Quest.*CourierPotionLo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string quests {
            get {
                return ResourceManager.GetString("quests", resourceCulture);
            }
        }
    }
}
